In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.datasets import load_digits
digits=load_digits()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

SVM

In [4]:
model_svm=SVC()
model_svm.fit(X_train,y_train)
model_svm.score(X_test,y_test)

0.9888888888888889

Random Forest

In [5]:
model_RF=RandomForestClassifier()
model_RF.fit(X_train,y_train)
model_RF.score(X_test,y_test)

0.9805555555555555

Logistic Regression 

In [6]:
model_LR=LogisticRegression()
model_LR.fit(X_train,y_train)
model_LR.score(X_test,y_test)

c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

With Function 

In [7]:
def get_score(model,X_train,y_train,X_test,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [8]:
get_score(SVC(),X_train,y_train,X_test,y_test)

0.9888888888888889

In [9]:
get_score(LogisticRegression(),X_train,y_train,X_test,y_test)

c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

In [10]:
get_score(RandomForestClassifier(),X_train,y_train,X_test,y_test)

0.9833333333333333

In [15]:
from sklearn.model_selection import KFold
Kf=KFold(n_splits=3)
Kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
for train_split,test_split in Kf.split([1,2,3,4,5,6]):
    print(train_split,test_split)

[2 3 4 5] [0 1]
[0 1 4 5] [2 3]
[0 1 2 3] [4 5]


In [23]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [28]:
Score_SVM=[]
Score_Logistic=[]
Score_Random=[]

for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    Score_Logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,y_train,X_test,y_test))
    Score_SVM.append(get_score(SVC(gamma='auto'),X_train,y_train,X_test,y_test))
    Score_Random.append(get_score(RandomForestClassifier(n_estimators=80),X_train,y_train,X_test,y_test))
    

c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [29]:
Score_SVM

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [32]:
Score_Random

[0.9348914858096828, 0.9449081803005008, 0.9215358931552587]

In [31]:
Score_Logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [37]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver="liblinear",multi_class="ovr"),digits.data,digits.target,cv=3)


c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\evilk\OneDrive\Desktop\ML\myvenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


array([0.89482471, 0.95325543, 0.90984975])

In [38]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)


array([0.38063439, 0.41068447, 0.51252087])

In [41]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=3)


array([0.93823038, 0.94323873, 0.92821369])